### ISSUE TITLE
SEO, meta data

### ISSUE THREAD

**Issue by hannah26hannah** [hannah26hannah/hannah-as-dev#16]
- [x] index layout's meta data
- [x] Add blog posts' specific meta data
- [x] update new meta image 
- [x] open graph tags
